### PR TITLE
Keeps default formatting on list leads

### LINKED ISSUE #7: List item leads contain formatting
Even when the text is selected, if a `bulletedLineStarter` or a `numberedLineStarter` is in the selection, it should always maintain a regular font.  Right now it will change the formatting.

### PR DESCRIPTION
**Pull request by SerenadeX**
Fixes #7

### CODE REVIEW

**Comment by nickmshelley** [comment]
Why aren't any of your tests running?

**Comment by SerenadeX** [comment]
There are no tests

**Comment by SerenadeX** [comment]
The only "checks" were with gitmagic which is a tool to regulate how your issues, PRs, and commits are supposed to look.

**Comment by nickmshelley** [comment]
Oh I guess I was thinking of https://github.com/LyokoTech/TSSwiftMarkdownParser

**Comment by SerenadeX** [comment]
Yeah that guy has tests.  This one still needs tests written

**Comment by digbads** [comment]
👍

**Pull request merged**
